
DROP TABLE MEMBER3
CASCADE CONSTRAINTS;

CREATE TABLE MEMBER3(
	ID VARCHAR2(50) PRIMARY KEY,
	PWD VARCHAR2(50) NOT NULL,
	NAME VARCHAR2(50) NOT NULL,
	EMAIL VARCHAR2(50) UNIQUE,
	AUTH NUMBER(1) NOT NULL
);

SELECT * FROM MEMBER3;