DROP TABLE EXHIBIT
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_EXHIBIT;

-- EXHIBIT TABLE
CREATE TABLE EXHIBIT (
    SEQ NUMBER(8) PRIMARY KEY,
    BEGINDATE DATE NOT NULL,
    ENDDATE DATE NOT NULL,
    TITLE VARCHAR2(200) NOT NULL,
    PLACE VARCHAR2(50) NOT NULL,
    CONTENT VARCHAR2(4000) NOT NULL,
    EX_TIME VARCHAR2(50) NOT NULL,
    LOC_INFO VARCHAR2(100) NOT NULL, 
    DEL NUMBER(2) NOT NULL,
    CONTACT VARCHAR2(20),
    CERTI_NUM VARCHAR2(50) NOT NULL,
    PRICE NUMBER(8)
);
-- ���Ἲ
ALTER TABLE EXHIBIT
ADD CONSTRAINT FK_EXHIBIT_CERTINUM FOREIGN KEY (CERTI_NUM)
REFERENCES MEMBER(CERTI_NUM);

-- UNIQUE
ALTER TABLE EXHIBIT
ADD CONSTRAINT UK_EXHIBIT_TITLE UNIQUE(TITLE);

-- EXHIBIT SEQ
CREATE SEQUENCE SEQ_EXHIBIT
START WITH 1
INCREMENT BY 1;


SELECT * FROM EXHIBIT
