
DROP TABLE FILES 
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_FILES;

-- 파일 테이블 생성
CREATE TABLE FILES (
    SEQ NUMBER(8)  NOT NULL,
    FILENAME VARCHAR2(500)  PRIMARY KEY,
    ORIGIN_NAME VARCHAR2(500) NOT NULL,    
    FILEPATH VARCHAR2(500),
    BBS_NAME VARCHAR2(20),
    BBS_SEQ VARCHAR2(8),
    DEL NUMBER(2) NOT NULL
);

CREATE SEQUENCE SEQ_FILES 
START WITH 1 
INCREMENT BY 1;


SELECT * FROM FILES
