-- 삭제
DROP TABLE RESERVATION
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_RESV;

-- 생성
CREATE TABLE RESERVATION(
	SEQ NUMBER(8) PRIMARY KEY,
	ID VARCHAR2(20) NOT NULL,
	NAME VARCHAR2(20) NOT NULL,
	BIRTHDATE VARCHAR2(20) NOT NULL,
	PHONE VARCHAR2(20) NOT NULL,
	EMAIL VARCHAR2(30) NOT NULL,
	ADDRESS VARCHAR2(100) NOT NULL,
	RECEIVE VARCHAR2(30) NOT NULL,
	QTY NUMBER(8) NOT NULL,
	TOTAL_PRICE NUMBER(20) NOT NULL,
	PAY_METHOD VARCHAR2(30) NOT NULL,
	DEL NUMBER(2),
	TITLE VARCHAR2(200) NOT NULL,
	RDATE DATE NOT NULL,
	DURING VARCHAR2(200) NOT NULL
	
);

-- 무결성
ALTER TABLE RESERVATION 
ADD CONSTRAINT FK_RESERV_ID FOREIGN KEY (ID)
REFERENCES MEMBER(ID);


-- 시퀀스
CREATE SEQUENCE SEQ_RESV
START WITH 1
INCREMENT BY 1;

-- 전시명 추가 
-- ALTER TABLE RESERVATION ADD TITLE VARCHAR2(200);

-- 예매시간 추가 -> 오라클에서 NOT NULL로 바꿈
-- ALTER TABLE RESERVATION ADD RDATE DATE;

-- 전시기간 추가 
-- ALTER TABLE RESERVATION ADD DURING VARCHAR2(200);

SELECT * FROM RESERVATION;
