

CREATE TABLE NOTICE(
	SEQ NUMBER(8) PRIMARY KEY,
	REF NUMBER(8) NOT NULL,
	ID VARCHAR2(30) NOT NULL,
	TITLE VARCHAR2(200) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	REG_DATE DATE NOT NULL,
	READCOUNT NUMBER(8)	NOT NULL,
	DEL NUMBER(8) NOT NULL,
	CHOICE NUMBER(8) NOT NULL
	
);

CREATE SEQUENCE SEQ_NOTICE
START WITH 1
INCREMENT BY 1;

ALTER TABLE NOTICE
ADD CONSTRAINT FK_NOTICE_ID FOREIGN KEY(ID)
REFERENCES MEMBER(ID);

SELECT * FROM NOTICE;

DROP TABLE NOTICE
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_NOTICE;

INSERT INTO NOTICE (SEQ,REF,ID,TITLE,CONTENT,REG_DATE,READCOUNT,DEL,CHOICE)
VALUES(SEQ_NOTICE.NEXTVAL, 'admin', 'test', '전시회관련', SYSDATE, 0, 0 , 1);

SELECT NVL(MAX(REF),0)+1 FROM NOTICE;

